input.onButtonPressed(Button.AB, function () {
    music.setVolume(255)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(831, music.beat(BeatFraction.Whole))
    music.playTone(740, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(831, music.beat(BeatFraction.Whole))
    music.playTone(740, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(50)
    music.playTone(466, music.beat(BeatFraction.Whole))
})
